global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "splitwise-backend"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["backend:8080"]
        labels:
          application: "splitease"
          environment: "prod"

  - job_name: "prometheus"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["localhost:9090"]
